### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Amateur-God** [drndos/hass-openai-custom-conversation#6]
i put in the http://IP:Port of my local AI instance however this results in just getting an unknown error

**Comment by Amateur-God** [comment]
logs data

```
Logger: custom_components.custom_openai_conversation.config_flow
Source: custom_components/custom_openai_conversation/config_flow.py:90
Integration: custom_openai_conversation ([documentation](https://github.com/drndos/hass-openai-custom-conversation), [issues](https://github.com/drndos/hass-openai-custom-conversation/issues))
First occurred: 09:51:02 (19 occurrences)
Last logged: 10:32:17

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/custom_openai_conversation/config_flow.py", line 90, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/custom_openai_conversation/config_flow.py", line 70, in validate_input
    await hass.async_add_executor_job(partial(openai.Model.list))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/lib/_old_api.py", line 39, in __call__
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

**Comment by swittk** [comment]
yeah same
